name: Build Test Image

on:
  pull_request:
    branches:
      - main
  merge_group:
    types:
      - checks_requested

jobs:
  build:
    name: Build Test Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: docker/setup-buildx-action@6a58db7e0d21ca03e6c44877909e80e45217eed2 # v2.6.0

      - id: docker_build
        uses: docker/build-push-action@2eb1c1961a95fc15694676618e422e8ba1d63825 # v4.1.1
        with:
          context: .
          load: true
          push: false
          tags: kineticcafe/ansible:test

      - run: ./run --version
        env:
          IMAGE: kineticcafe/ansible:test
